[DATA]
DATA_PATH='data'
TRAIN_FOLDER_NAME='train'
VALID_FOLDER_NAME='valid'
TEST_FOLDER_NAME='test'
CLEAN_FOLDER_NAME='clean'
NOISY_FOLDER_NAME='noisy'
DENOISE_MODEL_PATH='models\denoise_model.pth'


[TRAIN]
EPOCHS=50
LEARNING_RATE=0.0003
BATCH_SIZE=64
INPUT_LABEL='input'
OUTPUT_LABEL='output'
SIGNAL_LENGTH='initial_length'
